name: Racket CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        racket-version: [ '6.12', '7.0', '7.3', '7.4', '7.5', '7.6', '7.7', '7.8' ]
        racket-variant: [ 'BC' ]
        experimental: [false]
        include:
          - racket-version: '8.0'
            racket-variant: 'CS'
            experimental: false
          - racket-version: '8.1'
            racket-variant: 'CS'
            experimental: false
          - racket-version: 'current'
            racket-variant: 'CS'
            experimental: true
    name: Racket ${{ matrix.racket-version }} ${{ matrix.racket-variant }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.4
        with:
          architecture: 'x64'
          version: ${{ matrix.racket-version }}
          variant: ${{ matrix.racket-variant }}
      - run: raco pkg install -t dir gen-queue-lib/ graph-lib/ graph-test/
      - run: raco test -p graph-test
